version: '3.9'

networks:
  modelvault-net:
    driver: bridge

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-container
    networks:
      - modelvault-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: modelvault
      MYSQL_ROOT_PASSWORD: yourpassword

  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: minio-container
    networks:
      - modelvault-net
    ports:
      - "9000:9000"
      - "9001:9001"

  moderegistry:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moderegistry-container
    networks:
      - modelvault-net
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/modelvault?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yourpassword
      MINIO_URL: http://minio-container:9000
      MINIO_ACCESS-KEY: minioadmin
      MINIO_SECRET-KEY: minioadmin
    depends_on:
      - mysql
      - minio